services:
  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:latest
    pull_policy: always
    restart: unless-stopped
    networks:
      - networking
      - tools
    #ports:
    #  - 8084:80
    environment:
      - TZ=${TZ}
    labels:
      - "org.label-schema.group=tools"
      - "traefik.enable=true"
      - "traefik.docker.network=networking"
      # HTTP Routers
      - "traefik.http.routers.it-tools-router.entrypoints=websecure"
      - "traefik.http.routers.it-tools-router.rule=Host(`it-tools.$DOMAINNAME_1`)" # HostRegexp:it-tools.${DOMAINNAME_1},{catchall:.*}" # Host(`it-tools.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.it-tools-router.middlewares=secure-headers@file"
      #- "traefik.http.routers.it-tools-router.middlewares=authentik-traefik@file"
      # HTTP Services
      - "traefik.http.routers.it-tools-router.service=it-tools-service"
      - "traefik.http.services.it-tools-service.loadbalancer.server.port=80"
      - homepage.group=DevOps
      - homepage.name=It Tools
      - homepage.icon=it-tools.svg
      - homepage.href=https://it-tools.$DOMAINNAME_1
      - homepage.description=It Tools
      - homepage.showStats=true
