networks:
  tools:
    external: true  

services:
  semaphoreui:
    image: semaphoreui/semaphore:latest 
    pull_policy: always
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    container_name: semaphoreui
    #ports:
    #  - 3000:3000
    networks:
      - tools
      - networking
    environment:
      - TZ=${TZ}
      - SEMAPHORE_EMAIL_HOST=mail.${DOMAINNAME_1}
      - SEMAPHORE_EMAIL_PORT=587
      - SEMAPHORE_EMAIL_SECURE=true
      - SEMAPHORE_EMAIL_USERNAME=${SEMAPHORE_SMTP_USER}
      - SEMAPHORE_EMAIL_PASSWORD=${SEMAPHORE_SMTP_PASSWORD}
      - SEMAPHORE_EMAIL_SENDER=semaphoreui@${DOMAINNAME_1}
      - SEMAPHORE_DB_DIALECT=bolt
      - SEMAPHORE_ADMIN=admin
      - SEMAPHORE_ADMIN_PASSWORD=${SEMAPHORE_ADMIN_PASSWORD}
      - SEMAPHORE_ADMIN_NAME="Semaphore Admin"
      - SEMAPHORE_ADMIN_EMAIL=admin@${DOMAINNAME_1}
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
      - SEMAPHORE_TELEGRAM_ALERT="True"
      - SEMAPHORE_TELEGRAM_CHAT=${SEMAPHORE_TELEGRAM_CHAT}
      - SEMAPHORE_TELEGRAM_TOKEN=${SEMAPHORE_TELEGRAM_CHAT}
    volumes:
      - semaphoreui-data:/var/lib/semaphore
      - semaphoreui-config:/etc/semaphore
      - semaphoreui-tmp:/tmp/semaphore
    labels:
      - "org.label-schema.group=tools"
      - "traefik.enable=true"
      - "traefik.docker.network=networking"
      # HTTP Routers
      - "traefik.http.routers.semaphoreui-router.entrypoints=websecure"
      - "traefik.http.routers.semaphoreui-router.rule=Host(`semaphoreui.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.semaphoreui-router.middlewares=secure-headers@file"
      # HTTP Services
      - "traefik.http.routers.semaphoreui-router.service=semaphoreui-service"
      - "traefik.http.services.semaphoreui-service.loadbalancer.server.port=3000"
      - homepage.group=DevOps
      - homepage.name=Semaphore UI
      - homepage.icon=semaphore.svg
      - homepage.href=https://semaphoreui.$DOMAINNAME_1
      - homepage.description=Semaphore UI
      - homepage.showStats=true

volumes:
  semaphoreui-config:
    external: true
  semaphoreui-data:
    external: true
  semaphoreui-tmp:
    external: true
