networks:
  networking:
    external: true
  management:
    external: true
  monitoring:
    external: true
  security:
    external: true
  tools:
    external: true
  databases:
    external: true
  storage:
    external: true
  mediaserver:
    external: true

include:
  # Crowdsec
  - crowdsec.yaml
  # Vaultwarden
  - vaultwarden.yaml
  # ClamAV
  - clamav.yaml
  # Openbao
  - openbao.yaml
